### ISSUE TITLE
Automação de calculo de valor futuro

### ISSUE THREAD

**Issue by arturbersan** [DreamRich/DreamRich#12]
Implementar a fórmula de valor futuro seguindo [as 3 variações](http://keisan.casio.com/exec/system/1234231998).
- [x]  Deixar brecha para que caso não seja passado o PMT ou o PV seja atribuido o valor '0' para o calculo.

**Comment by marcelohpf** [comment]
Possível solução! Para #14 #13 

https://docs.scipy.org/doc/numpy/reference/routines.financial.html

**Comment by marcelohpf** [comment]
O numpy implementa as fórmulas!
closes #14 #13
