### ISSUE TITLE
Submissão de endereço não está funcionando

### ISSUE THREAD

**Issue by icaropires** [DreamRich/DreamRich#125]
## Descrição
A submissão de endereço via api não está funcionando corretamente. Acontece um erro de integridade na chave estrangeira state_id da tabela de relacionamento client_address. Isso possívelmente se dá devido a ordem de submissão dos formulários ou pode ser necessário mexer na serialização.

## O que foi tentado
- Verificar se realmente está sendo enviado um state_id válido no formulário do endereço;

## Como reproduzir
Tente submeter o formulário de cadastro do cliente com todos campos do cliente ativo e endereço válidos

**Comment by marcelohpf** [comment]
Fixed in unstable and add type_of_address fetch backend in branch is125
