### ISSUE TITLE
Serializar diferença ao final entre o ganho atual para o ganho sugerido

### ISSUE THREAD

**Issue by arturbersan** [DreamRich/DreamRich#154]
- [ ] Aportes Totais até Aposentadoria (cédula N76)
- [ ] Juros Ganhos Cenário Atual (cédula N77)
- [ ] Juros Ganhos Rentabilidade Sugerida (cedula N78)
- [ ] Diferença % (O78)
- [ ] Diferença R$ (P78)

**Comment by marcelohpf** [comment]
close when #170 merged
