### ISSUE TITLE
Fazer com que a classe PrivatePension seja uma especialização da Active

### ISSUE THREAD

**Issue by arturbersan** [DreamRich/DreamRich#155]
- [x] Fazer uma herança entre Active e PrivatePension
- [x] Adaptar as factories para que seja correto o item anterior consertando os testes
- [x] Renomear os atributos de ambas classes para que faça sentido
- [x] Consertar os testes o item anterior
- [ ] No método save do PrivatePension fazer com que seja atribuido ao ActiveType com nome PREVIDÊNCIA
- [ ] Testar o item anterior

**Comment by marcelohpf** [comment]
close when #170 merged
