### ISSUE TITLE
Consertar novos erros de checagem

### ISSUE THREAD

**Issue by icaropires** [DreamRich/DreamRich#185]
- [x] Remover ignores do pylint de arquivo todo ou que não deveriam existir
- [x] Consertar todos erros do pylint
- [x] Consertar erros de folha de estilo
- [x] Fazer build passar
- [x] Escrever script que roda os testes e faz todas checkagens (pré pull request)
- [x] Renomear scripts seed para load
- [x] Fazer script geral para loads

**Comment by marcelohpf** [comment]
#192
