### ISSUE TITLE
Permissões de acesso a rota

### ISSUE THREAD

**Issue by arturbersan** [DreamRich/DreamRich#52]
Não permitir que rotas sejam acessadas por usuários que não devem ter permissão de acesso a elas
- [x] see_all_basic_client_data - get nos dados básicos de todos os clientes
- [x] change_own_client_data - get/post/put em todos os dados do clientes que tem relacionamento com a instancia em questão
- [x] see_own_client_data - get em todos os dados do client

**Comment by marcelohpf** [comment]
Feitos para react, falta adicionar as validações nas views do django
